FROM golang:trixie AS builder

WORKDIR /build

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
	   build-essential cmake ninja-build llvm-dev \
	   ca-certificates zlib1g-dev libzstd-dev \
	&& rm -rf /var/lib/apt/lists/*

COPY CMakeLists.txt /build
COPY ./cmake /build/cmake
COPY ./src /build/src

RUN cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DDOCKER_BUILD=ON \
	&& cmake --build build --target bfc -j$(nproc)

COPY ./web/server.go /build/src/server.go

RUN CGO_ENABLED=0 GOOS=linux go build -o build/server src/server.go

FROM debian:trixie-slim
WORKDIR /app

COPY --from=builder /build/build/server /app/server
COPY --from=builder /build/build/bfc /app/bfc

EXPOSE 8000
ENTRYPOINT [ "/app/server", "/app/bfc" ]
